version: '2.1'

services:
  zoo1:
    image: zookeeper:3.4.9
    container_name: zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - /DATA1/zookeeper/zoo1/data:/data
      - /DATA1/zookeeper/zoo1/datalog:/datalog
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.2

  zoo2:
    image: zookeeper:3.4.9
    container_name: zoo2
    hostname: zoo2
    ports:
      - "2182:2182"
    environment:
        ZOO_MY_ID: 2
        ZOO_PORT: 2182
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - /DATA1/zookeeper/zoo2/data:/data
      - /DATA1/zookeeper/zoo2/datalog:/datalog 
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.3

  zoo3:
    image: zookeeper:3.4.9
    container_name: zoo3
    hostname: zoo3
    ports:
      - "2183:2183"
    environment:
        ZOO_MY_ID: 3
        ZOO_PORT: 2183
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - /DATA1/zookeeper/zoo3/data:/data
      - /DATA1/zookeeper/zoo3/datalog:/datalog
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.4

  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://217.24.19.69:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - /DATA2/kafka/kafka1/data:/var/lib/kafka/data
      - config-kafka-1:/etc/kafka
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.5
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://217.24.19.69:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - /DATA2/kafka/kafka2/data:/var/lib/kafka/data
      - config-kafka-2:/etc/kafka
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.6
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka3:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://217.24.19.69:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - /DATA2/kafka/kafka3/data:/var/lib/kafka/data
      - config-kafka-3:/etc/kafka
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.7
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  kafka-manager:
    image: kafkamanager/kafka-manager:latest
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: 'zoo1:2181,zoo2:2181,zoo3:2181'
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.8
    depends_on:
      - kafka1
      - kafka2
      - kafka3
  kowl:
    image: quay.io/cloudhut/kowl:v1.1.0
    container_name: kowl
    restart: unless-stopped
    hostname: kowl
    volumes:
      - ./kowl/config.yml:/etc/kowl/config.yaml
    ports:
      - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    networks:
      kafka_cluster:
        ipv4_address: 172.21.0.9
    depends_on:
      - kafka1
      - kafka2
      - kafka3

volumes:
  config-kafka-1:
    driver: local
  config-kafka-2:
    driver: local
  config-kafka-3:
    driver: local
networks:
  kafka_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
